### PR TITLE
Appdata rename

### PR DESCRIPTION
**Pull request by maxice8**
The rationale is stored in the commit's messages, most specifically in the first one

### CODE REVIEW

**Comment by karlch** [comment]
Thanks for pointing this out!

**Comment by maxice8** [comment]
Another thing, the specification says the id should be an unique identifier (so not just the name, otherwise forks will conflict).

So in the future it might be worth using something like `org.karlch.vimiv.metainfo.xml`

**Comment by karlch** [comment]
This also makes sense to me, although I am not very fond of adding my username in here. I guess it should also be unique between this legacy Gtk version and the newer [qt port](https://github.com/karlch/vimiv-qt).

Maybe just `org.vimiv.gtk.metainfo.xml` and `org.vimiv.qt.metainfo.xml` and forks can just call themselves `org.vimiv.forkid.metainfo.xml`?

**Comment by maxice8** [comment]
well, most people use their name or the name of the organization like org.gnome (i have lots of those).

I also don't know what forkid should be

**Comment by karlch** [comment]
I thought this could be up to the fork, e.g. if you would maintain one and like to call it after your username `org.vimiv.maxice8.metainfo.xml`.

If it is common practice to use the username though, I am not fully reluctant to `org.karlch.vimiv.metainfo`. Although there would probably still need to be some differentiation between the gtk and the qt port.

**Comment by maxice8** [comment]
well if i forked vimiv then it would be `org.maxice8.vimiv`. It is not obligatory but using your name or organization is what is most used.

could be vimiv-qt or vimiv-gtk ?

**Comment by karlch** [comment]
If I read the standard you linked in the commit correctly, hyphens are discouraged. It seems like underscores could be valid, so maybe:
`org.karlch.vimiv_gtk.metainfo` and `org.karlch.vimiv_qt.metainfo`.
Or just dots:
`org.karlch.vimiv.gtk.metainfo` and `org.karlch.vimiv.qt.metainfo`.

This is somehow more complicated than expected :smiley: Thanks for your help!

**Comment by karlch** [comment]
I have adjusted this in the two referenced commits for the corresponding fork. Thanks again!

**Pull request merged**
